backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'channel'
    label: 'Streaming Channel'
    format: 'json'
    folder: 'content/channel'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Live Streaming URL', name: 'url', widget: 'string' }
      - { label: 'Start Event Date', name: 'date', widget: 'datetime' }
  - name: 'speakers'
    label: 'Speaker'
    format: 'json'
    folder: 'content/speakers'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Jabatan', name: 'title', widget: 'string' }
      - { label: 'Topik', name: 'topics', widget: 'string' }
      - { label: 'Tanggal & Jam', name: 'date', widget: 'datetime' }
      - { label: 'City Base', name: 'cities', widget: 'select', options: [
        "GDG Bandung", "GDG Jakarta", "GDG Surabaya", "GDG Bali", "GDG Makassar", "GDG Depok", "GDG Bogor", "GDG Yogyakarta", "GDG Semarang" ,"GDG Cloud Bandung", "GDG Cloud Jakarta", "GDG Cloud Surabaya"
      ] }
